import {
    AlertTriangle,
    ArrowRight,
    Building2,
    Check,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    CreditCard,
    File,
    FileText,
    HelpCircle,
    Home,
    Image,
    Laptop,
    LayoutDashboard,
    LayoutGrid,
    Loader2,
    Menu,
    Moon,
    MoreHorizontal,
    MoreVertical,
    PackageSearch,
    Pizza,
    Plus,
    Settings,
    ShoppingBag,
    SunMedium,
    Sword,
    Trash,
    Twitter,
    User,
    Users,
    X,
} from "lucide-react";

export const Icons = {
    close: X,
    spinner: Loader2,
    chevronLeft: ChevronLeft,
    chevronDown: ChevronDown,
    chevronUp: ChevronUp,
    chevronRight: ChevronRight,
    trash: Trash,
    post: FileText,
    home: Home,
    page: File,
    media: Image,
    menu: Menu,
    settings: Settings,
    billing: CreditCard,
    moreHorizontal: MoreHorizontal,
    ellipsis: MoreVertical,
    add: Plus,
    warning: AlertTriangle,
    user: User,
    layoutGrid: LayoutGrid,
    users: Users,
    arrowRight: ArrowRight,
    help: HelpCircle,
    pizza: Pizza,
    product: PackageSearch,
    dashboard: LayoutDashboard,
    shoppingBag: ShoppingBag,
    sun: SunMedium,
    moon: Moon,
    challenge: Sword,
    laptop: Laptop,
    brand: Building2,
    twitter: Twitter,
    check: Check,
};
